copy_week3:
	mkdir week3
	cp week3_greedy_algorithms/*/*.py week3/

copy_week4:
	mkdir week4
	cp week4_divide_and_conquer/*/*.py week4/

copy_week5:
	mkdir week5
	cp week5_dynamic_programming1/*/*.py week5/