copy_week1:
	mkdir week1
	cp week1_basic_data_structures/*/*.py week1/

copy_week2:
	mkdir week2
	cp week2_priority_queues_and_disjoint_sets/*/*.py week2/

copy_week3:
	mkdir week3
	cp week3_hash_tables/*/*.py week3/
